#define __MAX_VA__ 32
#define __VA_ENTRIES_0__
#define __VA_ENTRIES_1__ __VA_ENTRIES_0__ __VA_ENTRY__(0)
#define __VA_ENTRIES_2__ __VA_ENTRIES_1__ __VA_ENTRY__(1)
#define __VA_ENTRIES_3__ __VA_ENTRIES_2__ __VA_ENTRY__(2)
#define __VA_ENTRIES_4__ __VA_ENTRIES_3__ __VA_ENTRY__(3)
#define __VA_ENTRIES_5__ __VA_ENTRIES_4__ __VA_ENTRY__(4)
#define __VA_ENTRIES_6__ __VA_ENTRIES_5__ __VA_ENTRY__(5)
#define __VA_ENTRIES_7__ __VA_ENTRIES_6__ __VA_ENTRY__(6)
#define __VA_ENTRIES_8__ __VA_ENTRIES_7__ __VA_ENTRY__(7)
#define __VA_ENTRIES_9__ __VA_ENTRIES_8__ __VA_ENTRY__(8)
#define __VA_ENTRIES_10__ __VA_ENTRIES_9__ __VA_ENTRY__(9)
#define __VA_ENTRIES_11__ __VA_ENTRIES_10__ __VA_ENTRY__(10)
#define __VA_ENTRIES_12__ __VA_ENTRIES_11__ __VA_ENTRY__(11)
#define __VA_ENTRIES_13__ __VA_ENTRIES_12__ __VA_ENTRY__(12)
#define __VA_ENTRIES_14__ __VA_ENTRIES_13__ __VA_ENTRY__(13)
#define __VA_ENTRIES_15__ __VA_ENTRIES_14__ __VA_ENTRY__(14)
#define __VA_ENTRIES_16__ __VA_ENTRIES_15__ __VA_ENTRY__(15)
#define __VA_ENTRIES_17__ __VA_ENTRIES_16__ __VA_ENTRY__(16)
#define __VA_ENTRIES_18__ __VA_ENTRIES_17__ __VA_ENTRY__(17)
#define __VA_ENTRIES_19__ __VA_ENTRIES_18__ __VA_ENTRY__(18)
#define __VA_ENTRIES_20__ __VA_ENTRIES_19__ __VA_ENTRY__(19)
#define __VA_ENTRIES_21__ __VA_ENTRIES_20__ __VA_ENTRY__(20)
#define __VA_ENTRIES_22__ __VA_ENTRIES_21__ __VA_ENTRY__(21)
#define __VA_ENTRIES_23__ __VA_ENTRIES_22__ __VA_ENTRY__(22)
#define __VA_ENTRIES_24__ __VA_ENTRIES_23__ __VA_ENTRY__(23)
#define __VA_ENTRIES_25__ __VA_ENTRIES_24__ __VA_ENTRY__(24)
#define __VA_ENTRIES_26__ __VA_ENTRIES_25__ __VA_ENTRY__(25)
#define __VA_ENTRIES_27__ __VA_ENTRIES_26__ __VA_ENTRY__(26)
#define __VA_ENTRIES_28__ __VA_ENTRIES_27__ __VA_ENTRY__(27)
#define __VA_ENTRIES_29__ __VA_ENTRIES_28__ __VA_ENTRY__(28)
#define __VA_ENTRIES_30__ __VA_ENTRIES_29__ __VA_ENTRY__(29)
#define __VA_ENTRIES_31__ __VA_ENTRIES_30__ __VA_ENTRY__(30)
#define __VA_ENTRIES_32__ __VA_ENTRIES_31__ __VA_ENTRY__(31)
#define __DO_VA_CASES_0__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 0)
#define __DO_VA_CASES_1__(retstyle, funcname) __DO_VA_CASES_0__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 1)
#define __DO_VA_CASES_2__(retstyle, funcname) __DO_VA_CASES_1__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 2)
#define __DO_VA_CASES_3__(retstyle, funcname) __DO_VA_CASES_2__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 3)
#define __DO_VA_CASES_4__(retstyle, funcname) __DO_VA_CASES_3__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 4)
#define __DO_VA_CASES_5__(retstyle, funcname) __DO_VA_CASES_4__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 5)
#define __DO_VA_CASES_6__(retstyle, funcname) __DO_VA_CASES_5__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 6)
#define __DO_VA_CASES_7__(retstyle, funcname) __DO_VA_CASES_6__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 7)
#define __DO_VA_CASES_8__(retstyle, funcname) __DO_VA_CASES_7__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 8)
#define __DO_VA_CASES_9__(retstyle, funcname) __DO_VA_CASES_8__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 9)
#define __DO_VA_CASES_10__(retstyle, funcname) __DO_VA_CASES_9__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 10)
#define __DO_VA_CASES_11__(retstyle, funcname) __DO_VA_CASES_10__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 11)
#define __DO_VA_CASES_12__(retstyle, funcname) __DO_VA_CASES_11__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 12)
#define __DO_VA_CASES_13__(retstyle, funcname) __DO_VA_CASES_12__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 13)
#define __DO_VA_CASES_14__(retstyle, funcname) __DO_VA_CASES_13__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 14)
#define __DO_VA_CASES_15__(retstyle, funcname) __DO_VA_CASES_14__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 15)
#define __DO_VA_CASES_16__(retstyle, funcname) __DO_VA_CASES_15__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 16)
#define __DO_VA_CASES_17__(retstyle, funcname) __DO_VA_CASES_16__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 17)
#define __DO_VA_CASES_18__(retstyle, funcname) __DO_VA_CASES_17__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 18)
#define __DO_VA_CASES_19__(retstyle, funcname) __DO_VA_CASES_18__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 19)
#define __DO_VA_CASES_20__(retstyle, funcname) __DO_VA_CASES_19__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 20)
#define __DO_VA_CASES_21__(retstyle, funcname) __DO_VA_CASES_20__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 21)
#define __DO_VA_CASES_22__(retstyle, funcname) __DO_VA_CASES_21__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 22)
#define __DO_VA_CASES_23__(retstyle, funcname) __DO_VA_CASES_22__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 23)
#define __DO_VA_CASES_24__(retstyle, funcname) __DO_VA_CASES_23__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 24)
#define __DO_VA_CASES_25__(retstyle, funcname) __DO_VA_CASES_24__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 25)
#define __DO_VA_CASES_26__(retstyle, funcname) __DO_VA_CASES_25__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 26)
#define __DO_VA_CASES_27__(retstyle, funcname) __DO_VA_CASES_26__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 27)
#define __DO_VA_CASES_28__(retstyle, funcname) __DO_VA_CASES_27__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 28)
#define __DO_VA_CASES_29__(retstyle, funcname) __DO_VA_CASES_28__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 29)
#define __DO_VA_CASES_30__(retstyle, funcname) __DO_VA_CASES_29__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 30)
#define __DO_VA_CASES_31__(retstyle, funcname) __DO_VA_CASES_30__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 31)
#define __DO_VA_CASES_32__(retstyle, funcname) __DO_VA_CASES_31__(retstyle, funcname) __DO_VA_CASE__(retstyle, funcname, 32)
#define __DO_ALL_VA_CASES__(retstyle, funcname) __DO_VA_CASES_32__(retstyle, funcname)
